# European Voltage Defaults
# Configuration template for European electrical standards (IEC 60038) 
# Use this as a base for European installations
# Test configuration for frequency implementation and European defaults

substitutions:
  # Device configuration  
  name: "european-ups-test"
  friendly_name: "European UPS Test"
  
  # European electrical standards
  nominal_voltage: "230V"     # Standard European single-phase voltage (IEC 60038)
  frequency: "50Hz"           # European frequency standard
  
  # Regional timezone examples (adjust for your location)
  timezone: "Europe/Warsaw"   # Poland
  # timezone: "Europe/Vienna"   # Austria
  # timezone: "Europe/Berlin"   # Germany
  # timezone: "Europe/London"   # United Kingdom  
  # timezone: "Europe/Paris"    # France
  # timezone: "Europe/Rome"     # Italy
  # timezone: "Europe/Madrid"   # Spain

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: "Testing European defaults and frequency implementation"

# Core ESP32 configuration
esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# External components
external_components:
  - source:
      type: local
      path: ../../components

# Base UPS configuration with European defaults
ups_hid:
  id: ups_monitor
  update_interval: 30s
  protocol_timeout: 15s
  protocol: auto
  fallback_nominal_voltage: ${nominal_voltage}
  simulation_mode: false

# Time configuration with European timezone
time:
  - platform: sntp
    id: sntp_time
    timezone: ${timezone}
    servers:
      - "pool.ntp.org"
      - "time.nist.gov"

# Logging optimized for European users
logger:
  level: INFO
  logs:
    ups_hid: INFO

# WiFi configuration template
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "${friendly_name} AP"
    password: !secret ap_password

# Optional: Home Assistant API with encryption
api:
  encryption:
    key: !secret api_encryption_key

# Optional: Over-the-air updates    
ota:
  - platform: esphome
    password: !secret ota_password