# UPS Control Buttons Package with Entity Grouping
# Organized beeper control and UPS testing functionality
# Use with: packages: !include configs/ups_controls_grouped.yaml

button:
  # === BEEPER CONTROL GROUP ===
  - platform: ups_hid
    ups_hid_id: ups_monitor
    beeper_action: enable
    name: "UPS Beeper Enable"
    icon: "mdi:volume-high"
    web_server:
      sorting_group_id: ups_beeper_controls
      sorting_weight: 10
    
  - platform: ups_hid
    ups_hid_id: ups_monitor
    beeper_action: disable
    name: "UPS Beeper Disable"
    icon: "mdi:volume-off"
    web_server:
      sorting_group_id: ups_beeper_controls
      sorting_weight: 20
    
  - platform: ups_hid
    ups_hid_id: ups_monitor
    beeper_action: mute
    name: "UPS Beeper Mute"
    icon: "mdi:volume-mute"
    web_server:
      sorting_group_id: ups_beeper_controls
      sorting_weight: 30
    # Note: Only effective during active alarms
    
  - platform: ups_hid
    ups_hid_id: ups_monitor
    beeper_action: test
    name: "UPS Beeper Test"
    icon: "mdi:bell-ring"
    web_server:
      sorting_group_id: ups_beeper_controls
      sorting_weight: 40

  # === TEST CONTROL GROUP ===
  - platform: ups_hid
    ups_hid_id: ups_monitor
    test_action: battery_quick
    name: "UPS Quick Battery Test"
    icon: "mdi:battery-check"
    web_server:
      sorting_group_id: ups_test_controls
      sorting_weight: 10
    
  - platform: ups_hid
    ups_hid_id: ups_monitor
    test_action: battery_deep
    name: "UPS Deep Battery Test"
    icon: "mdi:battery-plus"
    web_server:
      sorting_group_id: ups_test_controls
      sorting_weight: 20
    
  - platform: ups_hid
    ups_hid_id: ups_monitor
    test_action: battery_stop
    name: "UPS Stop Battery Test"
    icon: "mdi:battery-remove"
    web_server:
      sorting_group_id: ups_test_controls
      sorting_weight: 30
    
  - platform: ups_hid
    ups_hid_id: ups_monitor
    test_action: ups_test
    name: "UPS Panel Test"
    icon: "mdi:test-tube"
    web_server:
      sorting_group_id: ups_test_controls
      sorting_weight: 40
    
  - platform: ups_hid
    ups_hid_id: ups_monitor
    test_action: ups_stop
    name: "UPS Stop Panel Test"
    icon: "mdi:stop"
    web_server:
      sorting_group_id: ups_test_controls
      sorting_weight: 50

# === TEST CONTROL GROUP - Result Monitoring ===
text_sensor:
  - platform: ups_hid
    ups_hid_id: ups_monitor
    name: "UPS Test Result"
    id: ups_test_result
    type: ups_test_result
    icon: "mdi:test-tube"
    web_server:
      sorting_group_id: ups_test_controls
      sorting_weight: 60